Python 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> def slope_of_cubic(coefficients, x):
...     a, b, c, d = coefficients
...     return 3 * a * x**2 + 2 * b * x + c
... 
>>> coefficients = tuple(map(float, input("Enter the coefficients (a, b, c, d) separated by spaces: ").split()))
Enter the coefficients (a, b, c, d) separated by spaces: 2 3 4 5
>>> x = float(input("Enter the value of x: "))
Enter the value of x: 6
>>> slope = slope_of_cubic(coefficients, x)
... 
>>> print("The slope of the cubic polynomial at x =", x, "is", slope)
... 
... 
... 
... 
... 
... 
The slope of the cubic polynomial at x = 6.0 is 256.0